name: Pipeline Limitando Triggers:
on:
  push:
    branches: #[main, develop]
      - main
      - develop
jobs:
  outro-job:
    name: Teste
    runs-on: ubuntu-latest
    steps:
      - run: echo "oi"
